*** Variables ***
${LOGIN_TITLE}          The Internet

# Login Page Locators
${USERNAME_FIELD}       //input[@placeholder='อีเมล']
${PASSWORD_FIELD}       //input[@placeholder='รหัสผ่าน (ความยาว 6-15 ตัวอักษร)']
${LOGIN_BUTTON}         //a[@class='btn btn-small']
${LOGOUT_BUTTON}        //a[@class='button secondary radius']
${MESSAGE}              //div[@id='flash']
${HEADER_LOGIN}         //h2[normalize-space()='Login Page']
